### ISSUE TITLE
[前台商家頁面] /{merchant} introimage 無法顯示

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#1]
## 問題描述

response 有 但是卻沒出來
產品內頁卻有顯示image
## 重現方法

1. 
2. 
3. 

## 螢幕截圖

![螢幕快照 2019-09-20 下午3 54 56](https://user-images.githubusercontent.com/2792565/65310034-f3617e00-dbbf-11e9-8b57-6a9c29bc418e.png)
![螢幕快照 2019-09-20 下午3 55 16](https://user-images.githubusercontent.com/2792565/65310040-f5c3d800-dbbf-11e9-9511-1055e7917f3c.png)

**Comment by jjjj4564** [comment]
因為css background-image 不支援中文url
還是後端會把檔名重寫
如果使用者上傳相同檔名的檔案會多後綴(1)嗎

https://codepen.io/Zat-lu/pen/aboPXPR

**Comment by ppuff1988** [comment]
重複上傳的後綴會多(1)
中文目前後端不處理，所以可能要上傳的時候就要限制了！

**Comment by jjjj4564** [comment]
> 重複上傳的後綴會多(1)
> 中文目前後端不處理，所以可能要上傳的時候就要限制了！

好 前端處理寫法就好

**Comment by jjjj4564** [comment]
更正是空白名稱的問題 不是中文
