### ISSUE TITLE
[前台/活動] 未上架與新增中的活動要從前台排除

### ISSUE THREAD

**Issue by jjjj4564** [DaydreamLab/dingsomething-issues--internal#11]
## 問題描述
未上架與新增中的活動要從前台排除

## 重現方法

1. 
2. 
3. 

## 螢幕截圖

![螢幕快照 2019-10-05 上午11 46 22](https://user-images.githubusercontent.com/31230074/66249431-ecad3c00-e765-11e9-9978-31eecfa3e2db.png)
![螢幕快照 2019-10-05 上午11 49 50](https://user-images.githubusercontent.com/31230074/66249451-47df2e80-e766-11e9-844d-ea01062e2ba8.png)

**Comment by littlegreening** [comment]
新增中應該也要排除

**Comment by ppuff1988** [comment]
這個連同票種（開放 未開放）一併修好了
