### ISSUE TITLE
[後台/綁定金流] 藍新成功綁定轉址路徑錯誤

### ISSUE THREAD

**Issue by jjjj4564** [DaydreamLab/dingsomething-issues--internal#15]
後台的藍新成功綁定路徑錯誤

現在 admin.demo.dingsomething.com/bindCardSuccess
正確 admin.demo.dingsomething.com/merchant/:orderId/success

## 重現方法

1. 
2. 
3. 

## 螢幕截圖

admin.demo.dingsomething.com/bindCardSuccess
![螢幕快照 2019-10-05 下午2 03 31](https://user-images.githubusercontent.com/31230074/66250741-f7250100-e778-11e9-8554-e259413c528f.png)

**Comment by ppuff1988** [comment]
問題已修正
