### ISSUE TITLE
[前台付款頁面] 無法付款 

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#2]
## 問題描述

會有個popup 顯示訂單已取消
## 重現方法

1. 先到後台建立一張訂單
2. 點擊連結到前臺結帳 

## 螢幕截圖

![螢幕快照 2019-09-23 下午5 51 10](https://user-images.githubusercontent.com/2792565/65416742-18a5f480-de2b-11e9-90ac-9b8f44fca7ce.png)

**Comment by jjjj4564** [comment]
修正了 狀態id判斷錯誤
