### ISSUE TITLE
[後台訂單新增] source 的值沒有送 manual

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#3]
## 問題描述

如標題，會導致資料庫預設為 source 為 site

## 螢幕截圖

![螢幕快照 2019-09-23 下午7 15 59](https://user-images.githubusercontent.com/2792565/65421706-fa45f600-de36-11e9-88f1-4325ae99c000.png)

**Comment by littlegreening** [comment]
所以是因為要區分 LINE bot 來的訂單所以要多送 source 的值嗎？

**Comment by ppuff1988** [comment]
我在想好像也可以我自己補上去！
當初好像有的地方會顯示是哪邊來的
site
manual
linebot
我這邊先自己補上去好了！

**Comment by littlegreening** [comment]
再請自行關閉 issue

**Comment by ppuff1988** [comment]
這邊後台訂單後端自己補送
