### ISSUE TITLE
[後台/訂單新增] 0元的訂單一樣會顯示發送付款連結成功

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#4]
## 問題描述

如標題，看有沒有需要依據response code 回傳種類，你這樣才好顯示

## 螢幕截圖

![螢幕快照 2019-09-23 下午5 45 02](https://user-images.githubusercontent.com/2792565/65421814-498c2680-de37-11e9-9b26-6bf70b8ebacb.png)

**Comment by littlegreening** [comment]
已修正
