### ISSUE TITLE
[後台/ 核銷票卷] 核銷已過期票卷會導致 preloading 一直轉

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#6]
## 問題描述

按下使用票卷後，會顯示票卷已過期，然後頁面就死掉囉！

## 螢幕截圖

![螢幕快照 2019-09-23 下午7 28 06](https://user-images.githubusercontent.com/2792565/65422300-a2a88a00-de38-11e9-840d-e354c3d6006f.png)

**Comment by littlegreening** [comment]
已修正
