### ISSUE TITLE
[後台/退款] refundValue NaN

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues--internal#7]
## 問題描述

測資為0元訂單，按下退款後，出現欄位無效

## 重現方法

1. 編輯項目 -> 查看此時段所有訂單 -> 我要退款/取消訂單 -> 退款0元訂單

## 螢幕截圖

![螢幕快照 2019-09-23 下午7 36 48](https://user-images.githubusercontent.com/2792565/65422590-8a853a80-de39-11e9-907a-c676c6a422b5.png)
![螢幕快照 2019-09-23 下午5 49 38](https://user-images.githubusercontent.com/2792565/65422597-8e18c180-de39-11e9-900e-2bdb52b6a6df.png)

### 其他資訊

會不會是因為沒填數值，導致 ‘’ 被轉成 NaN

**Comment by littlegreening** [comment]
已修正
