### ISSUE TITLE
[後台/編輯購買方案] 刪不掉的購買方案～

### ISSUE THREAD

**Issue by cocowuu** [DaydreamLab/dingsomething-issues--internal#9]
## 問題描述
進入編輯購買方案創立1個新的購買方案，按了多次儲存。
重整後，前台活動頁，突然多出2個複製的新方案。
回到後台重新整理，也多出現2個複製的方案。刪除後，確定後台剩3個方案，刷新前台，2個複製新方案並未消失。再次重整後台編輯購買方案頁，2個複製方案又再次出現

## 重現方法
列出如何重現問題的方法或操作步驟 
1. 編輯活動 > 購買方案 > 新增1個購買方案> 完成 > 儲存按三次
2. 重新整理前台 > 會出現三個新增的方案（出現問題）
3. 重新整理後台 > 被多複製的三個方案 > 刪除 > 儲存
4. 重新整理前台 > 方案並未被刪除（出現問題）
5. 重新整理後台 >回到第2步

## 預期結果

 1. 新增並儲存後，前台應該只會出現先前設定的方案和1個新增的方案
2. 回到後台刪除並儲存後，前後台方案數量應該要一致

**Comment by ppuff1988** [comment]
這個問題應該在這版本已經修復! 如果還有請 reopen issue
